Linear Regression [1]Decision Tree RegressorKNeighborsRegressorSupport Vector Regressor (SVR)Ridge Regression (or Bayesian Ridge

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [3]:
current_dir = Path.cwd()
file_path = current_dir.parent.parent / 'Datasets' / 'Regression datasets' / 'California Housing' / 'california_housing.csv'

df = pd.read_csv(file_path)

df.head(10)

,Unnamed: 0,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   20640 non-null  int64
 1   MedInc       20640 non-null  float64
 2   HouseAge     20640 non-null  float64
 3   AveRooms     20640 non-null  float64
 4   AveBedrms    20640 non-null  float64
 5   Population   20640 non-null  float64
 6   AveOccup     20640 non-null  float64
 7   Latitude     20640 non-null  float64
 8   Longitude    20640 non-null  float64
 9   MedHouseVal  20640 non-null  float64
dtypes: float64(9), int64(1)
memory usage: 1.6 MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

Unnamed: 0     0
MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [9]:
df = df.drop('Unnamed: 0', axis=1)

In [10]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [12]:
X = df.drop("MedHouseVal", axis=1)
y = df['MedHouseVal']

In [45]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pickle

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [33]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
scaler_path = Path.cwd().parent.parent/ "ML_models and scalers" / "Scalers" / "california_housing.pkl"

pickle.dump(scaler, open(scaler_path, 'wb'))

In [16]:
## LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6009790143129108
mean_absolute_error : 0.5366527228153435
mean_squared_error : 0.5444842122132871

In [26]:
# Using GridSearchCV

param_grid = {
    'fit_intercept': [True, False],
    'positive': [True, False]
}

grid = GridSearchCV(LinearRegression(), param_grid=param_grid, cv=5, verbose=2)

grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s

{'fit_intercept': True, 'positive': False}

In [27]:
model = LinearRegression(fit_intercept=True, positive=False)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6009790143129108
mean_absolute_error : 0.5366527228153435
mean_squared_error : 0.5444842122132871

In [32]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "California_Housing"/"linear_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [35]:
## Decision Tree Regressor

model = DecisionTreeRegressor()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6267744102919106
mean_absolute_error : 0.4570401380813953
mean_squared_error : 0.5092850964721173

In [38]:
# using GridSearchCV

param_grid = {
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'splitter': ['best', 'random'],
    'max_depth': [7,8,9,10, 11, 12, 13],
    'min_samples_split': [10, 20, 25, 30, 35],
}

grid = GridSearchCV(DecisionTreeRegressor(),param_grid=param_grid, cv=3, verbose=5, n_jobs=-1)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 3 folds for each of 210 candidates, totalling 630 fits

{'criterion': 'poisson',
 'max_depth': 10,
 'min_samples_split': 25,
 'splitter': 'best'}

In [40]:
model = DecisionTreeRegressor(criterion='poisson', max_depth=10, min_samples_split=25, splitter='best')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.7277476106082925
mean_absolute_error : 0.4010641743973573
mean_squared_error : 0.37150208404671714

In [41]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "California_Housing"/"tree_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [46]:
## KNeighborsRegressor

model = KNeighborsRegressor()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6995524587495723
mean_absolute_error : 0.4259775503875969
mean_squared_error : 0.40997578743250385

In [47]:
param_grid = {
    'n_neighbors':[5,7,9,11,13],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2] # 1 = Manhattan, 2 = Euclidean (only matters if metric='minkowski')
}


grid = GridSearchCV(KNeighborsRegressor(), param_grid=param_grid, cv=5, verbose=5)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 240 candidates, totalling 1200 fits
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.706 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.705 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.688 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.698 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.688 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.709 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.710 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.692 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.702 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.691 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.706 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.705 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.688 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.698 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.688 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.709 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.710 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.692 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.702 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.691 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.712 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.706 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.697 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.706 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.698 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.716 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.712 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.701 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.710 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.712 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.706 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.697 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.706 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.698 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.716 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.712 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.701 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.710 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.710 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.705 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.696 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.709 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.698 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.715 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.712 total time=   0.2s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.701 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.713 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.710 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.705 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.696 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.709 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.698 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.715 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.712 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.701 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.713 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.708 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.705 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.697 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.709 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.696 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.713 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.713 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.703 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.713 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.708 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.705 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.697 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.709 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.696 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.713 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.713 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.703 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.713 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.702 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.707 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.703 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.698 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.706 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.695 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.713 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.711 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.703 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.712 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.701 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.707 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.703 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.698 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.706 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.695 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.713 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.711 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.703 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.712 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.701 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.729 total time=   0.2s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.735 total time=   0.2s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.729 total time=   0.3s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.731 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.727 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.732 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.740 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.731 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.733 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.729 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.729 total time=   0.2s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.735 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.729 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.731 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.727 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.732 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.740 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.731 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.733 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.729 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.739 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.740 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.733 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.736 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.727 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.742 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.746 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.737 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.739 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.731 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.739 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.740 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.733 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.736 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.727 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.742 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.746 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.737 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.739 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.731 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.739 total time=   0.2s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.738 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.732 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.739 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.725 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.743 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.745 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.737 total time=   0.1s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.743 total time=   0.1s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.730 total time=   0.1s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.739 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.738 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.732 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.739 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.725 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.743 total time=   0.1s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.745 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.737 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.743 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.730 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.738 total time=   0.2s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.736 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.732 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.738 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.726 total time=   0.2s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.743 total time=   0.2s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.743 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.737 total time=   0.2s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.743 total time=   0.2s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.732 total time=   0.2s

{'algorithm': 'auto',
 'metric': 'manhattan',
 'n_neighbors': 9,
 'p': 1,
 'weights': 'distance'}

In [48]:
model = KNeighborsRegressor(algorithm='auto', metric='manhattan', n_neighbors=9, p=1, weights='distance')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.7413908302899435
mean_absolute_error : 0.3961278082197597
mean_squared_error : 0.35288522431532965

In [49]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "California_Housing"/"kNN_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [58]:
## Support Vector Regressor (SVR)

model = SVR()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.7416209399588087
mean_absolute_error : 0.39244257311378744
mean_squared_error : 0.3525712280939052

In [59]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "California_Housing"/"svr_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [ ]:
## Using GridSearchCV

# it will take too muchh time, thats why i'm ignoring :)

In [52]:
## Ridge Regression

model = Ridge()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6009840416141063
mean_absolute_error : 0.536642845538575
mean_squared_error : 0.5444773522078508

In [54]:
param_grid = {
    'solver' :['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'],
    'alpha' : np.logspace(-4, 4, 50),
    'fit_intercept': [True, False]
}

grid = GridSearchCV(Ridge(), param_grid=param_grid, cv=5, verbose=5)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 700 candidates, totalling 3500 fits
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.404 total time=   0.3s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.608 total time=   0.1s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.618 total time=   0.1s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-2.600 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-2.600 total time=   0.1s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-3.374 total time=   0.1s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-2.594 total time=   0.1s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-2.565 total time=   0.1s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-2.623 total time=   0.1s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.608 total time=   0.1s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.618 total time=   0.1s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-2.600 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-2.600 total time=   0.1s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-2.594 total time=   0.1s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-2.565 total time=   0.1s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-2.623 total time=   0.1s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.608 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.618 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.404 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.608 total time=   0.1s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.618 total time=   0.1s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.591 total time=   0.1s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-2.599 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-3.374 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-2.594 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-2.565 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-2.623 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=lsqr;, score=-2.599 total time=   0.0s

{'alpha': np.float64(339.3221771895323),
 'fit_intercept': True,
 'solver': 'lsqr'}

In [56]:
model = Ridge(alpha=339.3221771895323, fit_intercept=True, solver='lsqr')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.5972392061655951
mean_absolute_error : 0.5387135886810602
mean_squared_error : 0.5495873686034546

In [57]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "California_Housing"/"ridge_model.pkl"

pickle.dump(model, open(model_path, 'wb'))