In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
current_dir = Path.cwd()
file_path = current_dir.parent.parent / 'Datasets' / 'Regression datasets' / 'Concrete Data' / 'Concrete_Data.xls'

df = pd.read_excel(file_path, engine='xlrd')

df.head(10)

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.029847
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.698299
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.447770
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.854291
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.289790

In [4]:
new_columns =  [
    "cement",
    "slag",
    "fly_ash",
    "water",
    "superplasticizer",
    "coarse_aggregate",
    "fine_aggregate",
    "age",
    "strength"
]


df.columns = new_columns

In [5]:
df.head()

,cement,slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cement            1030 non-null   float64
 1   slag              1030 non-null   float64
 2   fly_ash           1030 non-null   float64
 3   water             1030 non-null   float64
 4   superplasticizer  1030 non-null   float64
 5   coarse_aggregate  1030 non-null   float64
 6   fine_aggregate    1030 non-null   float64
 7   age               1030 non-null   int64
 8   strength          1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [7]:
df.isnull().sum()

cement              0
slag                0
fly_ash             0
water               0
superplasticizer    0
coarse_aggregate    0
fine_aggregate      0
age                 0
strength            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(25)

In [10]:
X = df.drop('strength', axis=1)
y = df['strength']

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
import pickle

In [18]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10, test_size=0.25)

In [12]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
scaler_path = Path.cwd().parent.parent/ "ML_models and scalers" / "Scalers" / "concrete_scaler.pkl"

pickle.dump(scaler, open(scaler_path, 'wb'))

In [19]:
## LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6128899126006704
mean_absolute_error : 8.186575235450505
mean_squared_error : 104.92832620839133

In [20]:
# Using GridSearchCV

param_grid = {
    'fit_intercept': [True, False],
    'positive': [True, False]
}

grid = GridSearchCV(LinearRegression(), param_grid=param_grid, cv=5, verbose=2)

grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END ..................fit_intercept=True, positive=True; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=True, positive=False; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END .................fit_intercept=False, positive=True; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s
[CV] END ................fit_intercept=False, positive=False; total time=   0.0s

{'fit_intercept': True, 'positive': False}

In [21]:
model = LinearRegression(fit_intercept=True, positive=False)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6128899126006704
mean_absolute_error : 8.186575235450505
mean_squared_error : 104.92832620839133

In [22]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "Concrete"/"linear_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [27]:
## Decision Tree Regressor

model = DecisionTreeRegressor()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.8797892499240952
mean_absolute_error : 3.7900905486098186
mean_squared_error : 32.583787424553115

In [28]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "Concrete"/"tree_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [26]:
# using GridSearchCV

param_grid = {
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'splitter': ['best', 'random'],
    'max_depth': [7,8,9,10, 11, 12, 13],
    'min_samples_split': [10, 20, 25, 30, 35],
}

grid = GridSearchCV(DecisionTreeRegressor(),param_grid=param_grid, cv=3, verbose=5, n_jobs=-1)
grid.fit(X_train_scaled, y_train)
print(grid.best_params_)
print(grid.best_score_)

Fitting 3 folds for each of 210 candidates, totalling 630 fits
{'criterion': 'poisson', 'max_depth': 10, 'min_samples_split': 10, 'splitter': 'random'}
0.7625386010182592

In [25]:
model = DecisionTreeRegressor(criterion='squared_error', max_depth=9, min_samples_split=10, splitter='random')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.790924037036721
mean_absolute_error : 5.611660071348108
mean_squared_error : 56.671193952933585

In [29]:
## KNeighborsRegressor

model = KNeighborsRegressor()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.7533151486021105
mean_absolute_error : 6.553894365978019
mean_squared_error : 66.8652907808238

In [30]:
param_grid = {
    'n_neighbors':[5,7,9,11,13],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2] # 1 = Manhattan, 2 = Euclidean (only matters if metric='minkowski')
}


grid = GridSearchCV(KNeighborsRegressor(), param_grid=param_grid, cv=5, verbose=5)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 240 candidates, totalling 1200 fits
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.725 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.586 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.704 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.740 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=uniform;, score=0.687 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.766 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.682 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.721 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.767 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=1, weights=distance;, score=0.721 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.725 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.586 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.704 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.740 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=uniform;, score=0.687 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.766 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.682 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.721 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.767 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=5, p=2, weights=distance;, score=0.721 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.694 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.545 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.676 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.711 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=uniform;, score=0.646 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.761 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.673 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.714 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.757 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=1, weights=distance;, score=0.710 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.694 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.545 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.676 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.711 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=uniform;, score=0.646 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.761 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.673 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.714 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.757 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=7, p=2, weights=distance;, score=0.710 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.663 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.533 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.687 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.701 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=uniform;, score=0.623 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.752 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.671 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.722 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.747 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=1, weights=distance;, score=0.703 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.663 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.533 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.687 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.701 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=uniform;, score=0.623 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.752 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.671 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.722 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.747 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=9, p=2, weights=distance;, score=0.703 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.641 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.504 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.659 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.688 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=uniform;, score=0.633 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.741 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.655 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.707 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.731 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=1, weights=distance;, score=0.707 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.641 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.504 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.659 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.688 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=uniform;, score=0.633 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.741 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.655 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.707 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.731 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=11, p=2, weights=distance;, score=0.707 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.633 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.494 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.653 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.684 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=uniform;, score=0.641 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.738 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.661 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.706 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.729 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=1, weights=distance;, score=0.708 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.633 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.494 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.653 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.684 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=uniform;, score=0.641 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.738 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.661 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.706 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.729 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=13, p=2, weights=distance;, score=0.708 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.713 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.603 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.690 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.700 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=uniform;, score=0.672 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.739 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.678 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.697 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.718 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=1, weights=distance;, score=0.710 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.713 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.603 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.690 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.700 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=uniform;, score=0.672 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.739 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.678 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.697 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.718 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=5, p=2, weights=distance;, score=0.710 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.710 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.594 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.681 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.693 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=uniform;, score=0.655 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.748 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.684 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.700 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.722 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=1, weights=distance;, score=0.706 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.710 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.594 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.681 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.693 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=uniform;, score=0.655 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.748 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.684 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.700 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.722 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=7, p=2, weights=distance;, score=0.706 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.685 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.559 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.682 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.695 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=uniform;, score=0.643 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.750 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.685 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.701 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.721 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=1, weights=distance;, score=0.703 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.685 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.559 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.682 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.695 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=uniform;, score=0.643 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.750 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.685 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.701 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.721 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=9, p=2, weights=distance;, score=0.703 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.659 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.525 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.679 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.680 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=uniform;, score=0.647 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.743 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.673 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.706 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.711 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=manhattan, n_neighbors=11, p=1, weights=distance;, score=0.706 total time=   0.0s

{'algorithm': 'brute',
 'metric': 'euclidean',
 'n_neighbors': 5,
 'p': 1,
 'weights': 'distance'}

In [31]:
model = KNeighborsRegressor(algorithm='brute', metric='euclidean', n_neighbors=5, p=1, weights='distance')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.8030112619681574
mean_absolute_error : 5.492273492952563
mean_squared_error : 53.39488490844302

In [32]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "Concrete"/"kNN_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [33]:
## Support Vector Regressor (SVR)

model = SVR()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6677499568298142
mean_absolute_error : 7.335854323128224
mean_squared_error : 90.05820836838704

In [34]:
param_grid = {
    "kernel": ["linear", "rbf", "poly"],
    "C": [0.1, 1, 10, 100],
    "epsilon": [0.01, 0.1, 0.2, 0.5],
    "gamma": ["scale", "auto"]
}

grid = GridSearchCV(SVR(), param_grid=param_grid, cv=5, verbose=5)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 96 candidates, totalling 480 fits
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.520 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.555 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.623 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.131 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.156 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.127 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.173 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.166 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.164 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.520 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.555 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.623 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.155 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.131 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.170 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.169 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.164 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.520 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.624 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.566 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.131 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.156 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.127 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.173 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.166 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.165 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.520 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.624 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.566 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.155 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.169 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.168 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.165 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.519 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.624 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.156 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.127 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.173 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.167 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.167 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.577 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.519 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.624 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.159 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.157 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.155 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.131 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.169 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.169 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.166 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.575 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.518 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.557 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.621 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.568 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.131 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.160 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.158 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=0.155 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=0.124 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=0.172 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=0.166 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=0.168 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.575 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.518 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.557 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.621 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.568 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.130 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.160 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.158 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=0.154 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=0.126 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=0.169 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=0.168 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=0.168 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.590 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.512 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.484 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.564 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.557 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.591 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.446 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.432 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.477 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.466 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.590 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.512 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.484 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.564 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.557 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.591 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.445 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.436 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.471 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.470 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.592 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.512 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.486 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.563 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.558 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.591 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.447 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.433 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.477 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.466 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.592 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.512 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.486 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.563 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.557 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.611 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.591 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.445 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.437 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.471 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.470 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.592 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.509 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.487 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=scale, kernel=linear;, score=0.561 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.558 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.611 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=scale, kernel=rbf;, score=0.593 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.447 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.434 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.478 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.467 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=scale, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.592 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.509 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.487 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.701 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=auto, kernel=linear;, score=0.561 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.557 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.602 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=auto, kernel=rbf;, score=0.593 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.444 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.438 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.471 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.470 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.2, gamma=auto, kernel=poly;, score=0.466 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.591 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.514 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.488 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.700 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.561 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.629 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.557 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.603 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.594 total time=   0.0s

{'C': 100, 'epsilon': 0.5, 'gamma': 'scale', 'kernel': 'rbf'}

In [35]:
model = SVR(C=100, epsilon=0.5, gamma='scale', kernel='rbf')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.8867083187224074
mean_absolute_error : 3.9354438747834637
mean_squared_error : 30.7083356304523

In [36]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "Concrete"/"svr_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [37]:
## Ridge Regression

model = Ridge()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6134312327205529
mean_absolute_error : 8.186891756729512
mean_squared_error : 104.78159840157083

In [38]:
param_grid = {
    'solver' :['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'],
    'alpha' : np.logspace(-4, 4, 50),
    'fit_intercept': [True, False]
}

grid = GridSearchCV(Ridge(), param_grid=param_grid, cv=5, verbose=5)
grid.fit(X_train_scaled, y_train)
grid.best_params_

Fitting 5 folds for each of 700 candidates, totalling 3500 fits
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=auto;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=svd;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=cholesky;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=lsqr;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=sparse_cg;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=sag;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=True, solver=saga;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=auto;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=svd;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=cholesky;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=lsqr;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=sparse_cg;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=sag;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.0001, fit_intercept=False, solver=saga;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=auto;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=svd;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=cholesky;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=lsqr;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sparse_cg;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=sag;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=True, solver=saga;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=auto;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=svd;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=cholesky;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=lsqr;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sparse_cg;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=sag;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00014563484775012445, fit_intercept=False, solver=saga;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=auto;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=svd;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=cholesky;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=lsqr;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sparse_cg;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=sag;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.624 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.550 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.591 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.690 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=True, solver=saga;, score=0.565 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=auto;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=svd;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-4.064 total time=   0.0s
[CV 2/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-4.610 total time=   0.0s
[CV 3/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-4.036 total time=   0.0s
[CV 4/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-4.107 total time=   0.0s
[CV 5/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=cholesky;, score=-3.721 total time=   0.0s
[CV 1/5] END alpha=0.00021209508879201905, fit_intercept=False, solver=lsqr;, score=-4.064 total time=   0.0s

{'alpha': np.float64(0.8286427728546842),
 'fit_intercept': True,
 'solver': 'svd'}

In [39]:
model = Ridge(alpha=0.8286427728546842, fit_intercept=True, solver='svd')
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print(f'r2_score : {r2_score(y_test, y_pred)}')
print(f'mean_absolute_error : {mean_absolute_error(y_test, y_pred)}')
print(f'mean_squared_error : {mean_squared_error(y_test, y_pred)}')

r2_score : 0.6133465755293246
mean_absolute_error : 8.186766318650339
mean_squared_error : 104.80454520059837

In [40]:
model_path = Path.cwd().parent.parent/ "ML_models and scalers" / "ML_Models"/ "Concrete"/"ridge_model.pkl"

pickle.dump(model, open(model_path, 'wb'))

In [41]:
df.head()

,cement,slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [42]:
df.columns

Index(['cement', 'slag', 'fly_ash', 'water', 'superplasticizer',
       'coarse_aggregate', 'fine_aggregate', 'age', 'strength'],
      dtype='str')